import "../styles/reset.css"
import "../styles/main.scss"
import "../styles/header.scss"
import "../styles/project-card.scss"
import "../styles/blog.scss"
import "prismjs/themes/prism.css"
// import "prismjs/themes/prism-dark.css"

import { Prism } from "prismjs"
import "../js/html-toggle"
